apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-data
  namespace: pdf-qa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  resources:
    requests:
      storage: 5Gi
